In [1]:
#libraries needed
import pandas as pd
import numpy as np

#scikit
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn import preprocessing
from sklearn import metrics

In [2]:
df = pd.read_csv("cleaned_data_v5.csv", encoding="Latin-1")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 38 columns):
Unnamed: 0                       99492 non-null int64
race                             99492 non-null object
gender                           99492 non-null object
age                              99492 non-null object
days_in_hospital                 99492 non-null int64
num_lab_procedures               99492 non-null int64
num_not_lab_procedures           99492 non-null int64
num_current_medications          99492 non-null int64
num_outpatient_appointments      99492 non-null int64
num_previous_emergencies         99492 non-null int64
num_inpatient_overnight_stays    99492 non-null int64
number_diagnoses                 99492 non-null int64
metformin                        99492 non-null object
repaglinide                      99492 non-null object
nateglinide                      99492 non-null object
chlorpropamide                   99492 non-null object
glimepiride                      99492 non-null object
acetohexamide                    99492 non-null object
glipizide                        99492 non-null object
glyburide                        99492 non-null object
tolbutamide                      99492 non-null object
pioglitazone                     99492 non-null object
rosiglitazone                    99492 non-null object
acarbose                         99492 non-null object
miglitol                         99492 non-null object
troglitazone                     99492 non-null object
tolazamide                       99492 non-null object
examide                          99492 non-null object
citoglipton                      99492 non-null object
insulin                          99492 non-null object
glyburide-metformin              99492 non-null object
glipizide-metformin              99492 non-null object
glimepiride-pioglitazone         99492 non-null object
metformin-rosiglitazone          99492 non-null object
metformin-pioglitazone           99492 non-null object
change_in_meds                   99492 non-null object
diabates_med_prescribed          99492 non-null object
readmitted                       99492 non-null object
dtypes: int64(9), object(29)
memory usage: 28.8+ MB

In [4]:
df = df.drop(['Unnamed: 0'], axis=1)

In [5]:
#renaming 'age'
#[70-80) -> 70
#[60-70) -> 60
#[50-60) -> 90
#[80-90) -> 80
#[40-50) -> 40
#[30-40) -> 30
#[90-100) -> 90
#[20-30) -> 20
#[10-20) -> 10
#[0-10)-> 0
age_mapping = {'[70-80)': 70, '[60-70)': 60, '[50-60)':90, '[80-90)':80, '[40-50)': 40, '[30-40)': 30,'[90-100)': 90, '[20-30)': 20, '[10-20)': 10, '[0-10)': 0}
df.age = df.age.replace(age_mapping)

In [6]:
list_of_meds = ['metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone']

# renaming values in medicines
# change in dosage('dosage_increased', 'dosage_decreased') -> 1
# no change or not prescribed 'not_prescribed', no_change_dosage -> 0
new_values_meds = {"dosage_increased":3, "dosage_decreased":1 ,"no_change_dosage":2, "not_prescribed":0}
for medicine in list_of_meds:
    df[medicine] = df[medicine].replace(new_values_meds)

In [7]:
# renaming 'readmitted'
# readmitted ('>30', '<30') -> 1
# not readmitted  ('NO') -> 0
df.readmitted = df.readmitted.replace({'NO': 0, '>30': 2, '<30':1})

In [8]:
# renaming 'diabetes_med_prescribed'
# 'Yes' -> 1 
# 'No' -> 0
df = df.rename(columns={'diabates_med_prescribed': 'diabetes_med_prescribed'})
df.diabetes_med_prescribed = df.diabetes_med_prescribed.replace({'Yes': 1, 'No':0})

In [9]:
# renaming 'change_in_meds'
# 'Ch' -> 1
# 'No' -> 0
df.change_in_meds = df.change_in_meds.replace({'Ch': 1, 'No': 0})

Using Label Encoder for gender and race

In [10]:
#before
print(df.race.value_counts())
print(df.gender.value_counts())

Caucasian          76099
AfricanAmerican    19210
Hispanic            2037
Other               1505
Asian                641
Name: race, dtype: int64
Female    53575
Male      45917
Name: gender, dtype: int64

In [11]:
x = df.columns.values
le_gender = preprocessing.LabelEncoder()
le_race = preprocessing.LabelEncoder()
x_gender = le_gender.fit_transform(df.gender.values)
x_race = le_race.fit_transform(df.race.values)
df['gender'] = x_gender
df['race'] = x_race

In [12]:
def value_counter(dataset):
    for index in dataset.columns:
        print("---- Index: " + index + "----")
        print(dataset[index].value_counts(ascending=True))
value_counter(df)

---- Index: race----
1      641
4     1505
3     2037
0    19210
2    76099
Name: race, dtype: int64
---- Index: gender----
1    45917
0    53575
Name: gender, dtype: int64
---- Index: age----
0       160
10      682
20     1611
30     3699
40     9465
80    16800
90    19619
60    21988
70    25468
Name: age, dtype: int64
---- Index: days_in_hospital----
14     1018
13     1189
12     1427
11     1816
10     2291
9      2940
8      4297
7      5720
6      7366
5      9763
4     13605
1     13877
2     16841
3     17342
Name: days_in_hospital, dtype: int64
---- Index: num_lab_procedures----
121       1
120       1
129       1
118       1
107       1
132       1
126       1
114       2
104       3
113       3
111       3
108       4
109       4
106       5
105       6
103       6
102       8
99        9
100      13
101      13
98       25
96       28
97       31
95       44
94       45
92       46
93       56
91       61
90       65
89       71
       ...
63     1418
60     1561
59     1592
61     1604
34     1633
58     1668
57     1699
53     1763
56     1774
55     1786
52     1797
54     1828
35     1871
51     1877
50     1877
36     1912
48     2009
49     2019
37     2033
39     2059
42     2062
47     2070
41     2071
40     2142
46     2153
38     2164
45     2328
44     2448
43     2750
1      3146
Name: num_lab_procedures, Length: 118, dtype: int64
---- Index: num_not_lab_procedures----
5     2984
4     4098
6     4825
3     9269
2    12488
1    20328
0    45500
Name: num_not_lab_procedures, dtype: int64
---- Index: num_current_medications----
81       1
79       1
74       1
75       2
70       2
72       3
66       5
69       5
64       7
67       7
68       7
65      12
63      13
61      14
62      15
60      20
59      20
58      24
57      26
55      31
54      33
56      37
53      37
51      43
50      52
52      53
48      57
49      61
47      72
45      80
      ...
32     608
31     697
30     832
3      877
29     971
28    1212
4     1376
27    1414
26    1576
25    1857
5     1964
24    2074
23    2384
6     2632
22    2812
21    3163
7     3401
20    3608
19    3965
8     4266
18    4421
9     4802
17    4819
10    5244
16    5305
14    5579
15    5662
11    5664
12    5866
13    5929
Name: num_current_medications, Length: 75, dtype: int64
---- Index: num_outpatient_appointments----
42        1
39        1
38        1
37        1
34        1
28        1
40        1
36        2
35        2
33        2
29        2
26        2
25        2
23        2
27        3
24        3
19        3
18        5
22        5
20        7
21        7
17        8
16       15
15       20
14       28
12       30
13       31
11       41
10       57
9        83
8        98
7       155
6       299
5       525
4      1083
3      2021
2      3543
1      8409
0     82992
Name: num_outpatient_appointments, dtype: int64
---- Index: num_previous_emergencies----
63        1
64        1
46        1
42        1
37        1
29        1
28        1
24        1
54        1
76        1
25        2
21        2
15        3
14        3
20        4
19        4
16        5
18        5
22        6
12       10
13       12
11       23
9        33
10       34
8        50
7        73
6        94
5       192
4       374
3       722
2      2027
1      7615
0     88189
Name: num_previous_emergencies, dtype: int64
---- Index: num_inpatient_overnight_stays----
21        1
18        1
17        1
19        2
16        6
15        9
14       10
13       20
12       34
11       49
10       61
9       111
8       150
7       268
6       480
5       807
4      1607
3      3374
2      7472
1     19218
0     65811
Name: num_inpatient_overnight_stays, dtype: int64
---- Index: number_diagnoses----
14        7
15        8
12        9
11       11
10       16
13       16
16       40
1       214
2       983
3      2767
4      5388
6     10005
7     10196
8     10440
5     10698
9     48694
Name: number_diagnoses, dtype: int64
---- Index: metformin----
1      562
3     1039
2    17920
0    79971
Name: metformin, dtype: int64
---- Index: repaglinide----
1       45
3      109
2     1375
0    97963
Name: repaglinide, dtype: int64
---- Index: nateglinide----
1       11
3       23
2      662
0    98796
Name: nateglinide, dtype: int64
---- Index: chlorpropamide----
1        1
3        6
2       78
0    99407
Name: chlorpropamide, dtype: int64
---- Index: glimepiride----
1      186
3      321
2     4527
0    94458
Name: glimepiride, dtype: int64
---- Index: acetohexamide----
2        1
0    99491
Name: acetohexamide, dtype: int64
---- Index: glipizide----
1      544
3      754
2    11101
0    87093
Name: glipizide, dtype: int64
---- Index: glyburide----
1      546
3      794
2     9039
0    89113
Name: glyburide, dtype: int64
---- Index: tolbutamide----
2       22
0    99470
Name: tolbutamide, dtype: int64
---- Index: pioglitazone----
1      117
3      230
2     6829
0    92316
Name: pioglitazone, dtype: int64
---- Index: rosiglitazone----
1       84
3      175
2     5968
0    93265
Name: rosiglitazone, dtype: int64
---- Index: acarbose----
1        3
3       10
2      289
0    99190
Name: acarbose, dtype: int64
---- Index: miglitol----
3        2
1        5
2       31
0    99454
Name: miglitol, dtype: int64
---- Index: troglitazone----
2        3
0    99489
Name: troglitazone, dtype: int64
---- Index: tolazamide----
3        1
2       38
0    99453
Name: tolazamide, dtype: int64
---- Index: examide----
0    99492
Name: examide, dtype: int64
---- Index: citoglipton----
0    99492
Name: citoglipton, dtype: int64
---- Index: insulin----
3    11056
1    12039
2    29902
0    46495
Name: insulin, dtype: int64
---- Index: glyburide-metformin----
1        3
3        6
2      671
0    98812
Name: glyburide-metformin, dtype: int64
---- Index: glipizide-metformin----
2       13
0    99479
Name: glipizide-metformin, dtype: int64
---- Index: glimepiride-pioglitazone----
2        1
0    99491
Name: glimepiride-pioglitazone, dtype: int64
---- Index: metformin-rosiglitazone----
0    99492
Name: metformin-rosiglitazone, dtype: int64
---- Index: metformin-pioglitazone----
2        1
0    99491
Name: metformin-pioglitazone, dtype: int64
---- Index: change_in_meds----
1    45910
0    53582
Name: change_in_meds, dtype: int64
---- Index: diabetes_med_prescribed----
0    23001
1    76491
Name: diabetes_med_prescribed, dtype: int64
---- Index: readmitted----
1    11169
2    35007
0    53316
Name: readmitted, dtype: int64

In [13]:
#discretising number_diagnoses
df['number_diagnoses'] = np.where(df['number_diagnoses'].between(0,4), 0, df['number_diagnoses'])
df['number_diagnoses'] = np.where(df['number_diagnoses'].between(5,8), 1, df['number_diagnoses'])
df['number_diagnoses'] = np.where(df['number_diagnoses'].between(9,12), 2, df['number_diagnoses'])
df['number_diagnoses'] = np.where(df['number_diagnoses'] > 12, 3, df['number_diagnoses'])

#Source for all masking:
# https://stackoverflow.com/questions/46168450/replace-a-specific-range-of-values-in-a-pandas-dataframe

In [14]:
#discretising num_lab_procedures
df['num_lab_procedures'] = np.where(df['num_lab_procedures'].between(0,20), 0, df['num_lab_procedures'])
df['num_lab_procedures'] = np.where(df['num_lab_procedures'].between(21,40), 1, df['num_lab_procedures'])
df['num_lab_procedures'] = np.where(df['num_lab_procedures'].between(41,60), 2, df['num_lab_procedures'])
df['num_lab_procedures'] = np.where(df['num_lab_procedures'].between(61,80), 3, df['num_lab_procedures'])
df['num_lab_procedures'] = np.where(df['num_lab_procedures'] > 80, 4, df['num_lab_procedures'])

In [15]:
# discretising days_in_hospital
df['days_in_hospital'] = np.where(df['days_in_hospital'].between(0,10), 0, df['days_in_hospital'])
df['days_in_hospital'] = np.where(df['days_in_hospital'] > 10, 1, df['days_in_hospital'])

In [16]:
# discretising num_current_medications
df['num_current_medications'] = np.where(df['num_current_medications'].between(0,20), 0, df['num_current_medications'])
df['num_current_medications'] = np.where(df['num_current_medications'].between(21,40), 1, df['num_current_medications'])
df['num_current_medications'] = np.where(df['num_current_medications'].between(41,60), 2, df['num_current_medications'])
df['num_current_medications'] = np.where(df['num_current_medications'] > 60, 3, df['days_in_hospital'])

In [17]:
# discretising num_inpatient_overnight_stays
df['num_inpatient_overnight_stays'] = np.where(df['num_inpatient_overnight_stays'].between(0,10), 0, df['num_inpatient_overnight_stays'])
df['num_inpatient_overnight_stays'] = np.where(df['num_inpatient_overnight_stays'].between(11,20), 1, df['num_inpatient_overnight_stays'])
df['num_inpatient_overnight_stays'] = np.where(df['num_inpatient_overnight_stays'] > 20, 2, df['num_inpatient_overnight_stays'])

In [18]:
# discretising num_previous_emergencies
df['num_previous_emergencies'] = np.where(df['num_previous_emergencies'].between(0,20), 0, df['num_previous_emergencies'])
df['num_previous_emergencies'] = np.where(df['num_previous_emergencies'].between(21,40), 1, df['num_previous_emergencies'])
df['num_previous_emergencies'] = np.where(df['num_previous_emergencies'].between(41,60), 2, df['num_previous_emergencies'])
df['num_previous_emergencies'] = np.where(df['num_previous_emergencies'] > 60, 3, df['num_previous_emergencies'])

In [19]:
# discretising num_outpatient_appointments
df['num_outpatient_appointments'] = np.where(df['num_outpatient_appointments'].between(0,20), 0, df['num_outpatient_appointments'])
df['num_outpatient_appointments'] = np.where(df['num_outpatient_appointments'].between(21,40), 1, df['num_outpatient_appointments'])
df['num_outpatient_appointments'] = np.where(df['num_outpatient_appointments'] > 40, 2, df['num_outpatient_appointments'])

In [20]:
value_counter(df)

---- Index: race----
1      641
4     1505
3     2037
0    19210
2    76099
Name: race, dtype: int64
---- Index: gender----
1    45917
0    53575
Name: gender, dtype: int64
---- Index: age----
0       160
10      682
20     1611
30     3699
40     9465
80    16800
90    19619
60    21988
70    25468
Name: age, dtype: int64
---- Index: days_in_hospital----
1     5450
0    94042
Name: days_in_hospital, dtype: int64
---- Index: num_lab_procedures----
4     1907
0    14277
3    17084
1    27092
2    39132
Name: num_lab_procedures, dtype: int64
---- Index: num_not_lab_procedures----
5     2984
4     4098
6     4825
3     9269
2    12488
1    20328
0    45500
Name: num_not_lab_procedures, dtype: int64
---- Index: num_current_medications----
3       95
1     5411
0    93986
Name: num_current_medications, dtype: int64
---- Index: num_outpatient_appointments----
2        1
1       38
0    99453
Name: num_outpatient_appointments, dtype: int64
---- Index: num_previous_emergencies----
2        3
3        3
1       14
0    99472
Name: num_previous_emergencies, dtype: int64
---- Index: num_inpatient_overnight_stays----
2        1
1      132
0    99359
Name: num_inpatient_overnight_stays, dtype: int64
---- Index: number_diagnoses----
3       71
0     9352
1    41339
2    48730
Name: number_diagnoses, dtype: int64
---- Index: metformin----
1      562
3     1039
2    17920
0    79971
Name: metformin, dtype: int64
---- Index: repaglinide----
1       45
3      109
2     1375
0    97963
Name: repaglinide, dtype: int64
---- Index: nateglinide----
1       11
3       23
2      662
0    98796
Name: nateglinide, dtype: int64
---- Index: chlorpropamide----
1        1
3        6
2       78
0    99407
Name: chlorpropamide, dtype: int64
---- Index: glimepiride----
1      186
3      321
2     4527
0    94458
Name: glimepiride, dtype: int64
---- Index: acetohexamide----
2        1
0    99491
Name: acetohexamide, dtype: int64
---- Index: glipizide----
1      544
3      754
2    11101
0    87093
Name: glipizide, dtype: int64
---- Index: glyburide----
1      546
3      794
2     9039
0    89113
Name: glyburide, dtype: int64
---- Index: tolbutamide----
2       22
0    99470
Name: tolbutamide, dtype: int64
---- Index: pioglitazone----
1      117
3      230
2     6829
0    92316
Name: pioglitazone, dtype: int64
---- Index: rosiglitazone----
1       84
3      175
2     5968
0    93265
Name: rosiglitazone, dtype: int64
---- Index: acarbose----
1        3
3       10
2      289
0    99190
Name: acarbose, dtype: int64
---- Index: miglitol----
3        2
1        5
2       31
0    99454
Name: miglitol, dtype: int64
---- Index: troglitazone----
2        3
0    99489
Name: troglitazone, dtype: int64
---- Index: tolazamide----
3        1
2       38
0    99453
Name: tolazamide, dtype: int64
---- Index: examide----
0    99492
Name: examide, dtype: int64
---- Index: citoglipton----
0    99492
Name: citoglipton, dtype: int64
---- Index: insulin----
3    11056
1    12039
2    29902
0    46495
Name: insulin, dtype: int64
---- Index: glyburide-metformin----
1        3
3        6
2      671
0    98812
Name: glyburide-metformin, dtype: int64
---- Index: glipizide-metformin----
2       13
0    99479
Name: glipizide-metformin, dtype: int64
---- Index: glimepiride-pioglitazone----
2        1
0    99491
Name: glimepiride-pioglitazone, dtype: int64
---- Index: metformin-rosiglitazone----
0    99492
Name: metformin-rosiglitazone, dtype: int64
---- Index: metformin-pioglitazone----
2        1
0    99491
Name: metformin-pioglitazone, dtype: int64
---- Index: change_in_meds----
1    45910
0    53582
Name: change_in_meds, dtype: int64
---- Index: diabetes_med_prescribed----
0    23001
1    76491
Name: diabetes_med_prescribed, dtype: int64
---- Index: readmitted----
1    11169
2    35007
0    53316
Name: readmitted, dtype: int64

In [21]:
new_df_1 = pd.get_dummies(df)

value_counter(new_df_1)

In [23]:
#after
print(df.gender.value_counts())
print(df.race.value_counts())

0    53575
1    45917
Name: gender, dtype: int64
2    76099
0    19210
3     2037
4     1505
1      641
Name: race, dtype: int64

In [24]:
new_df_1.to_csv("cleaned_data_BN_v2.csv")

In [25]:
new_df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 37 columns):
race                             99492 non-null int64
gender                           99492 non-null int64
age                              99492 non-null int64
days_in_hospital                 99492 non-null int64
num_lab_procedures               99492 non-null int64
num_not_lab_procedures           99492 non-null int64
num_current_medications          99492 non-null int64
num_outpatient_appointments      99492 non-null int64
num_previous_emergencies         99492 non-null int64
num_inpatient_overnight_stays    99492 non-null int64
number_diagnoses                 99492 non-null int64
metformin                        99492 non-null int64
repaglinide                      99492 non-null int64
nateglinide                      99492 non-null int64
chlorpropamide                   99492 non-null int64
glimepiride                      99492 non-null int64
acetohexamide                    99492 non-null int64
glipizide                        99492 non-null int64
glyburide                        99492 non-null int64
tolbutamide                      99492 non-null int64
pioglitazone                     99492 non-null int64
rosiglitazone                    99492 non-null int64
acarbose                         99492 non-null int64
miglitol                         99492 non-null int64
troglitazone                     99492 non-null int64
tolazamide                       99492 non-null int64
examide                          99492 non-null int64
citoglipton                      99492 non-null int64
insulin                          99492 non-null int64
glyburide-metformin              99492 non-null int64
glipizide-metformin              99492 non-null int64
glimepiride-pioglitazone         99492 non-null int64
metformin-rosiglitazone          99492 non-null int64
metformin-pioglitazone           99492 non-null int64
change_in_meds                   99492 non-null int64
diabetes_med_prescribed          99492 non-null int64
readmitted                       99492 non-null int64
dtypes: int64(37)
memory usage: 28.1 MB

Sources used:
- Sebastian Raschka, 2015. Python Machine Learning.
- Dmitry Zinoviev, 2016. Data Science Essentials in Python.
- Validation and Model Selection notebook from week 7
- https://www.kaggle.com/mayu0116/hyper-parameters-tuning-of-dtree-rf-svm-knn
- https://www.ritchieng.com/machine-learning-efficiently-search-tuning-param/
- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.KBinsDiscretizer.html#sklearn.preprocessing.KBinsDiscretizer
- https://stackabuse.com/cross-validation-and-grid-search-for-model-selection-in-python/
- https://medium.com/30-days-of-machine-learning/day-3-k-nearest-neighbors-and-bias-variance-tradeoff-75f84d515bdb
- https://stackoverflow.com/questions/46168450/replace-a-specific-range-of-values-in-a-pandas-dataframe